#!/bin/bash
#
# named a network name service.
#
#
# chkconfig: 545 35 75
# description: a name server
#
if [ `id -u` -ne 0 ]; then
    echo "ERROR:For bind to port 53,must run as root." 
    exit 1 
fi 
case "$1" in

start) 
    if [ -x /usr/local/bind/sbin/named ]; then 
        /usr/local/bind/sbin/named -u bind -c /usr/local/bind/etc/named.conf && echo . && echo 'BIND server started.' 
    fi 
;; 

stop) 
    kill `cat /usr/local/bind/var/run/named.pid` && echo . && echo 'BIND server stopped.' 
;; 

restart) 
    echo . 
    echo "Restart BIND server" 
    $0 stop 
    sleep 10 
    $0 start 
;; 

reload)
    /usr/local/bind/sbin/rndc reload
;;

status)
    /usr/local/bind/sbin/rndc status
;;

*)
    echo "$0 start | stop | restart |reload |status" 
;;

esac