#!/bin/bash
# squid This shell script takes care of starting and stopping
# Squid Internet Object Cache
#
#chkconfig: 2345 61 61
# description: Squid Server on 80
# E-mail : fj8101@gmail.com
case "$1" in
    start)
        install_dir/squid/sbin/squid -D
    ;;
    stop)
        install_dir/squid/sbin/squid -k shutdown
        install_dir/squid/sbin/squid -k shutdown
    ;;
    restart)
        install_dir/squid/sbin/squid -k shutdown
        install_dir/squid/sbin/squid -k shutdown
        install_dir/squid/sbin/squid -D
    ;;
    reload)
        install_dir/squid/sbin/squid -k reconfigure
    ;;
    info)
        install_dir/squid/bin/squidclient -p 80 cache_object://localhost/info
    ;;
    *)
        echo "Usage: /etc/init.d/squid {start|stop|info|restart|reload}"
        exit 1
    ;;
esac

